### ISSUE TITLE
Why is there no Int module?

### ISSUE THREAD

**Issue by Kerl13** [ocaml/stdlib-shims#10]
Is there a reason why there is no `Int` module in stdlib-shims? It is not clear to me from https://github.com/ocaml/stdlib-shims/issues/9#issuecomment-522927232 if it should be part of the library or not.

I'd be happy to add the module if you are okay with it.

**Comment by dbuenzli** [comment]
From that comment:

> So as it stands the only thing this repo provides is the `Stdlib` name so that your projects can cope with the deprecation of `Pervasives` and compile cleanly pre and post 4.08.

There is no plan to add the new modules added in 4.08.

**Comment by Kerl13** [comment]
Ok sorry, but then I don't understand how to use this library

**Comment by dbuenzli** [comment]
The `Pervasives` module name was deprecated in favor of `Stdlib` in 4.08. Using `stdlib-shims` allows you to use `Stdlib` instead of `Pervasives` before 4.08. (e.g. `Stdlib.compare` instead of `Pervasives.compare`). This allows your code to support pre 4.08 and post 4.08 without getting warnings in your face. It does not however provide the new names that are being added in `Stdlib`.

**Comment by Kerl13** [comment]
Ok I get it! Thanks for the clarification :)

**Comment by dbuenzli** [comment]
You are welcome. Tried to clarify the readme in 4b19a3f8cabf28601d44f41e02263f8cc4386b6b
