### ISSUE TITLE
Is it related to stdcompat?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/stdlib-shims#9]
Hello,

Sorry for the maybe silly question, but what is the difference with stdcompat?
The README is super terse, so...

https://github.com/thierry-martinez/stdcompat

Not related, does stdlib-shims have non tail recursive code?

Thanks,
F.

**Comment by dbuenzli** [comment]
Initially we had planned to provide in this package the new modules that are *added* to the stdlib (e.g. `Stdlib.{Option,Result,Fun}`. Together with @diml we eventually decided against it thinking stdlib improvements would entice people to move faster towards new versions of OCaml. 

So as it stands the only thing this repo provides is the `Stdlib` name so that your projects can cope with the deprecation of `Pervasives` and compile cleanly pre and post 4.08.

**Comment by UnixJunkie** [comment]
Ok, thanks for the clarification.
And I already have a project with a use-case for this. :)
